### ISSUE TITLE
add class to body when a modal is open

### ISSUE THREAD

**Issue by ritz078** [pleerock/ng2-modal#7]
This will help in adding class like

```css
body.modal-open{
  overflow: hidden;
}
```

**Comment by pleerock** [comment]
You can use "in" class. Its being set right after modal is opened:

```html
.modal.in {
  overflow: hidden;
}
```

**Comment by ritz078** [comment]
<img width="1280" alt="screen shot 2016-08-03 at 9 21 57 pm" src="https://cloud.githubusercontent.com/assets/5389035/17391926/8b0d4fa8-5a37-11e6-92ac-90dd4b6846e2.png">
as you can see in the screenshot there is no class on the body. even when the modal is open in the left.

**Comment by TheFirstAvenger** [comment]
I assume you are looking for this because of the scrolling issue (when modal is up, scroll wheel scrolls background page, not modal). I manually added overflow: hidden to the body via the BrowserDomAdapter, and it locks both the background and the modal, it doesn't scroll the modal. Any pointers on how to get the modal to scroll and not the background?

**Comment by pleerock** [comment]
fixed in 0.0.12

**Comment by TheFirstAvenger** [comment]
@pleerock I see the code change you made to modal for this issue, but router-modal did not get the same update. I am still seeing the issue whereby scrolling on router-modal scrolls the background page, not the modal dialog, was this version supposed to resolve that?

**Comment by pleerock** [comment]
@TheFirstAvenger  fixed in 0.0.13
